logging:
  level:
    root: INFO

server.port: 8080
springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /swagger
    operations-sorter: method
  packages-to-scan: edu.ntnu.idatt2106_2023_06.backend.controller

kassal:
  api-key: your-api-key-here

spring:
  profiles:
    active: dev

  mail:
#    TODO: need to change the host when deploying.
    host: localhost
    port: 1025
#    Add the options below when authentication is needed
#    username: idatt2106
#    password: password

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          timeout: 3000
          connectiontimeout: 5000
          writetimeout: 5000
